# This file was generated by GoReleaser. DO NOT EDIT.
cask "shellguard" do
  name "shellguard"
  desc "MCP server for read-only shell access over SSH"
  homepage "https://github.com/jonchun/shellguard"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shellguard"

  on_macos do
    on_intel do
      url "https://github.com/jonchun/shellguard/releases/download/v#{version}/shellguard_darwin_amd64.tar.gz"
      sha256 "8042e64171f04854c80ce7abcec65a01cbba57685dc70b37ee85636dcc830cb4"
    end
    on_arm do
      url "https://github.com/jonchun/shellguard/releases/download/v#{version}/shellguard_darwin_arm64.tar.gz"
      sha256 "0a1ca989af7a9d756f619f2c2eaddffff38377cb8b5e8757d4c1f1f897251dbd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jonchun/shellguard/releases/download/v#{version}/shellguard_linux_amd64.tar.gz"
      sha256 "848e87dab9ccee85972f6ad29a034670bd041b3378b903d60efec2f2f6ce0f93"
    end
    on_arm do
      url "https://github.com/jonchun/shellguard/releases/download/v#{version}/shellguard_linux_arm64.tar.gz"
      sha256 "478d9f132b0955ede6a35b05cd9063e059b52ae7caa79eeefee6bde03c2ecb11"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shellguard"]
    end
  end

  # No zap stanza required
end
