# This file was generated by GoReleaser. DO NOT EDIT.
cask "shellguard" do
  version "0.9.3"

  on_macos do
    on_intel do
      sha256 "16cc8498ef69a3dadf8e171d787a1cad151c3d7bc844f1ccdcc35ef696858194"
      url "https://github.com/fawdyinc/shellguard/releases/download/v#{version}/shellguard_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eecadce87e93bad95b2cb198536d059240fafa9fb4cbf444a09357a4b2dfe847"
      url "https://github.com/fawdyinc/shellguard/releases/download/v#{version}/shellguard_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce85f1ea23d68bdf31ec2cf826e837b1fa83fda60949622d841b17484b777ef3"
      url "https://github.com/fawdyinc/shellguard/releases/download/v#{version}/shellguard_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a689be452fdcc7209f3aa6e529fd50cac075a370b82b1a5f7726fc22656b7e5"
      url "https://github.com/fawdyinc/shellguard/releases/download/v#{version}/shellguard_linux_arm64.tar.gz"
    end
  end

  name "shellguard"
  desc "MCP server for read-only shell access over SSH"
  homepage "https://github.com/fawdyinc/shellguard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shellguard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shellguard"]
    end
  end

  # No zap stanza required

end
