# This file was generated by GoReleaser. DO NOT EDIT.
cask "shellguard" do
  name "shellguard"
  desc "MCP server for read-only shell access over SSH"
  homepage "https://github.com/jonchun/shellguard"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shellguard"

  on_macos do
    on_intel do
      url "https://github.com/jonchun/shellguard/releases/download/v#{version}/shellguard_darwin_amd64.tar.gz"
      sha256 "e5245b510829daa9bc72cea9e9792abbadf7e584e8320573721061b6e2273397"
    end
    on_arm do
      url "https://github.com/jonchun/shellguard/releases/download/v#{version}/shellguard_darwin_arm64.tar.gz"
      sha256 "64d213f1c731140d8865bba859095ca2aa0b3bd84e7e209fa41877f135800c66"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jonchun/shellguard/releases/download/v#{version}/shellguard_linux_amd64.tar.gz"
      sha256 "2da5bd5e89bbede5ee167a04aae07270a93804f7b95e11418d093594cb6e4dd8"
    end
    on_arm do
      url "https://github.com/jonchun/shellguard/releases/download/v#{version}/shellguard_linux_arm64.tar.gz"
      sha256 "c16cb077ea4a6950734c97a3d0298a2ac21f0d8c5a734c9afd735a55a5035094"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shellguard"]
    end
  end

  # No zap stanza required
end
